---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: home
  namespace: web-app
spec:
  selector:
    matchLabels:
      app: home
  replicas: 2
  template:
    metadata:
      labels:
        app: home
    spec:
      containers:
      - name: home
        image: arieltar/flask-home
        imagePullPolicy: Always
        ports:
        - containerPort: 5000