apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-mongo
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce 
  volumeName: pv-mongo
  resources:
    requests:
      storage: 1Gi