pipeline {

  environment {
    dockerimagename = "arieltar/flask-app-2"
    dockerImage = ""
  }

  agent any

  stages {

    stage('Checkout Source') {
      steps {
        git 'https://github.com/finance-dataspider/devops.git'
      }
    }

    stage('Build image') {
      steps{
        script {
          dockerImage = docker.build(dockerimagename,"./src/python/webapp/app2")
        }
      }
    }

    stage('Pushing Image') {
      environment {
               registryCredential = 'dockerhub-reg'
           }
      steps{
        script {
          docker.withRegistry( 'https://registry.hub.docker.com', registryCredential ) {
            dockerImage.push("latest")
          }
        }
      }
    }

    stage('Deploying App to Kubernetes') {
      steps {
        script {
          kubernetesDeploy(configs: "src/python/webapp/app2/app_2_deployment.yaml", kubeconfigId: "kubernetes")
        }
      }
    }

  }

}