pipeline {

  environment {
    dockerimagename = "arieltar/flaskapp"
    dockerImage = ""
  }

  agent any

  stages {

    stage('Checkout Source') {
      steps {
        git 'https://github.com/finance-dataspider/devops.git'
      }
    }

    stage('Build image') {
      steps{
        script {
          def version = readFile 'version'
          def versions = version.split('\\.')
          def major = versions[0]
          def minor = versions[0] + '.' + versions[1]
          def patch = version.trim()
          docker.withRegistry('', 'dockerhub-reg') {
              def image = docker.build('arieltar/flaskapp:latest')
              image.push()
              image.push(major)
              image.push(minor)
              image.push(patch)
            }            
          }
        }
      }
    stage('Deploying App to Kubernetes') {
      steps {
        script {
          kubernetesDeploy(configs: "src/python/webapp/webapp_deployment.yaml", kubeconfigId: "kubernetes")
        }
      }
    }

  }

}