pipeline {
    agent any

    stages {

        stage("build") {

            steps{
                echo "START DOCKER IMAGE BUILD"
            }
        }
        stage("docker-push") {

            steps{
                echo "PUSH DOCKER IMAGE BUILD"   
            }
        }
        stage("deploy") {

            steps{
                echo "DEPLOY NEW DOCKER IMAGE BUILD ON K8S  "
            }
        }
    }
}