---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1
  namespace: web-app
spec:
  selector:
    matchLabels:
      app: app1
  replicas: 1
  template:
    metadata:
      labels:
        app: app1
    spec:
      containers:
      - name: app1
        image: arieltar/flask-app-1
        imagePullPolicy: Always
        ports:
        - containerPort: 5000